name: vtk-surface-data
channels:
  - conda-forge
  - defaults
dependencies:
  - clang_osx-64       # [osx]
  - clangxx_osx-64     # [osx]
  - gcc_linux-64       # [linux]
  - gxx_linux-64       # [linux]
  - vs2017_win-64      # [win]
  - python>=3.7,<3.8
  - vtk